/**
 * Generates drizzle/seed.sql from src/data/*.json.
 *
 * Exists so the database can be populated with NO local environment and no
 * connection string on this machine: generate the file, paste it into Neon's
 * SQL Editor, done. scripts/seed-content.ts remains the option for anyone who
 * does have DATABASE_URL locally.
 *
 * The output is idempotent (ON CONFLICT DO UPDATE), so pasting it twice is
 * harmless, and re-pasting after editing the JSON updates rows in place.
 *
 * Run with: npm run db:seed:sql
 */

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const root = join(here, '..')
const dataDir = join(root, 'src', 'data')
const read = (file: string) => JSON.parse(readFileSync(join(dataDir, file), 'utf8'))

/** Single-quote escaping. Postgres doubles the quote. */
const q = (value: string) => `'${value.replace(/'/g, "''")}'`

const nullable = (value: string | undefined | null) => (value == null ? 'NULL' : q(value))

/** Postgres text[] literal. */
const textArray = (values: string[] | undefined) =>
  !values || values.length === 0
    ? `'{}'::text[]`
    : `ARRAY[${values.map(q).join(', ')}]::text[]`

/** jsonb literal, or NULL. */
const jsonb = (value: unknown) =>
  value == null ? 'NULL' : `${q(JSON.stringify(value))}::jsonb`

const slug = (value: string) =>
  value.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '')

interface JsonProject {
  id: string; title: string; description: string; longDescription?: string
  category: string; featured: boolean; technologies: string[]
  links?: { github?: string; live?: string }; date: string
  images?: string[]; keyFeatures?: string[]
  impact?: Array<{ label: string; value: string }>
}
interface JsonSkill { category: string; proficiency: number; color: string; skills: string[] }
interface JsonTimelineItem {
  id: string; type: string; title: string; organization: string; location: string
  startDate: string; endDate?: string; description?: string[]
  technologies?: string[]; icon?: string
}

const projects: JsonProject[] = read('projects.json')
const skills: JsonSkill[] = read('skills.json')
const timeline: JsonTimelineItem[] = read('timeline.json')

const lines: string[] = [
  '-- Generated by scripts/generate-seed-sql.ts — do not edit by hand.',
  '-- Idempotent: safe to run more than once.',
  '-- Run drizzle/0000_*.sql first to create the tables.',
  '',
  'BEGIN;',
  '',
  '-- ------------------------------------------------------------- projects',
]

for (const [i, p] of projects.entries()) {
  lines.push(
    `INSERT INTO projects (id, title, description, long_description, category, featured, technologies, links, date, images, key_features, impact, published, position, updated_at) VALUES (` +
      [
        q(p.id), q(p.title), q(p.description), nullable(p.longDescription), q(p.category),
        String(p.featured), textArray(p.technologies), jsonb(p.links ?? null), q(p.date),
        textArray(p.images), textArray(p.keyFeatures), jsonb(p.impact ?? null),
        'true', String(i), 'now()',
      ].join(', ') +
      `)\nON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, long_description = EXCLUDED.long_description, category = EXCLUDED.category, featured = EXCLUDED.featured, technologies = EXCLUDED.technologies, links = EXCLUDED.links, date = EXCLUDED.date, images = EXCLUDED.images, key_features = EXCLUDED.key_features, impact = EXCLUDED.impact, position = EXCLUDED.position, updated_at = now();`
  )
}

lines.push('', '-- ------------------------------------------------- skill_categories')

for (const [i, s] of skills.entries()) {
  lines.push(
    `INSERT INTO skill_categories (id, category, proficiency, color, skills, published, position, updated_at) VALUES (` +
      [
        q(slug(s.category)), q(s.category), String(s.proficiency), q(s.color),
        textArray(s.skills), 'true', String(i), 'now()',
      ].join(', ') +
      `)\nON CONFLICT (id) DO UPDATE SET category = EXCLUDED.category, proficiency = EXCLUDED.proficiency, color = EXCLUDED.color, skills = EXCLUDED.skills, position = EXCLUDED.position, updated_at = now();`
  )
}

lines.push('', '-- -------------------------------------------------- timeline_items')

for (const [i, t] of timeline.entries()) {
  lines.push(
    `INSERT INTO timeline_items (id, type, title, organization, location, start_date, end_date, description, technologies, icon, published, position, updated_at) VALUES (` +
      [
        q(t.id), q(t.type), q(t.title), q(t.organization), q(t.location), q(t.startDate),
        nullable(t.endDate), textArray(t.description), textArray(t.technologies),
        nullable(t.icon), 'true', String(i), 'now()',
      ].join(', ') +
      `)\nON CONFLICT (id) DO UPDATE SET type = EXCLUDED.type, title = EXCLUDED.title, organization = EXCLUDED.organization, location = EXCLUDED.location, start_date = EXCLUDED.start_date, end_date = EXCLUDED.end_date, description = EXCLUDED.description, technologies = EXCLUDED.technologies, icon = EXCLUDED.icon, position = EXCLUDED.position, updated_at = now();`
  )
}

lines.push('', 'COMMIT;', '')

mkdirSync(join(root, 'drizzle'), { recursive: true })
const out = join(root, 'drizzle', 'seed.sql')
writeFileSync(out, lines.join('\n'), 'utf8')

console.log(
  `Wrote drizzle/seed.sql — ${projects.length} projects, ${skills.length} skill categories, ${timeline.length} timeline items.`
)
